# OQI Project - VRP Optimization Environment
# Conda environment file for the Full Optimizer project
#
# To create the environment:
#   conda env create -f requirements.yml
#
# To update the environment:
#   conda env update -f requirements.yml --prune

name: oqi_vrp_environment

channels:
  - conda-forge
  - defaults

dependencies:
  # Python core
  - python=3.11
  
  # Scientific computing core
  - numpy>=1.24.0
  - scipy>=1.10.0
  - pandas>=2.0.0
  
  # Optimization libraries
  - ortools>=9.5.0
  - pulp>=2.7.0
  - networkx>=3.0
  
  # Machine learning and data science
  - scikit-learn>=1.3.0
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  - plotly>=5.15.0
  
  # Jupyter and interactive development
  - jupyter>=1.0.0
  - jupyterlab>=4.0.0
  - notebook>=6.5.0
  - ipywidgets>=8.0.0
  
  # Excel and data I/O
  - openpyxl>=3.1.0
  - xlrd>=2.0.0
  - xlsxwriter>=3.1.0
  
  # Geographic and mapping
  - folium>=0.14.0
  - geopy>=2.3.0
  - geopandas>=0.13.0
  - shapely>=2.0.0
  
  # Web requests and APIs
  - requests>=2.31.0
  - urllib3>=2.0.0
  
  # PDF generation and QR codes
  - reportlab>=4.0.0
  
  # Database connectivity
  - sqlite>=3.42.0
  - sqlalchemy>=2.0.0
  
  # Parallel processing
  - joblib>=1.3.0
  - multiprocessing-logging>=0.3.0
  
  # Development tools
  - pytest>=7.4.0
  - black>=23.7.0
  - flake8>=6.0.0
  - mypy>=1.5.0
  
  # System utilities
  - psutil>=5.9.0
  - pathlib2>=2.3.0
  - configparser>=6.0.0
  
  # Pip dependencies (not available via conda)
  - pip>=23.2.0
  - pip:
    # PDF generation (latest version)
    - fpdf2>=2.8.0
    
    # QR code generation
    - qrcode[pil]>=8.2
    
    # Enhanced plotting
    - kaleido>=0.2.1
    
    # Memory profiling
    - memory-profiler>=0.61.0
    
    # Progress bars
    - tqdm>=4.66.0
    
    # Enhanced data structures
    - dataclasses-json>=0.6.0
    
    # Time series analysis
    - pytz>=2023.3
    
    # Additional optimization tools
    - pymoo>=0.6.0
    
    # Logging utilities
    - colorlog>=6.7.0
    
    # Configuration management
    - python-dotenv>=1.0.0
    
    # Excel advanced features
    - xlwings>=0.31.0
    
    # Enhanced JSON handling
    - ujson>=5.8.0
    
    # Database migrations
    - alembic>=1.12.0
    
    # Web framework (for future API development)
    - fastapi>=0.103.0
    - uvicorn>=0.23.0
    
    # Async support
    - aiofiles>=23.2.0
    - asyncio-mqtt>=0.16.0
    
    # Enhanced datetime handling
    - arrow>=1.2.3
    
    # Statistical analysis
    - pingouin>=0.5.3
    
    # Image processing (for visualization)
    - pillow>=10.0.0
    
    # Enhanced CSV handling
    - csvkit>=1.1.1
    
    # XML/HTML parsing
    - beautifulsoup4>=4.12.0
    - lxml>=4.9.0
    
    # Enhanced HTTP client
    - httpx>=0.24.0
    
    # Caching
    - diskcache>=5.6.0
    
    # Enhanced CLI tools
    - click>=8.1.0
    - rich>=13.5.0
    
    # Performance monitoring
    - py-spy>=0.3.14
    
    # Enhanced serialization
    - pickle5>=0.0.12
    
    # Email utilities (for notifications)
    - yagmail>=0.15.0
    
    # Enhanced file handling
    - pathspec>=0.11.0
    
    # Text processing
    - fuzzywuzzy>=0.18.0
    - python-levenshtein>=0.21.0
